### ISSUE TITLE
GitHubからStepippo-iOSリポジトリをCloneしてXcodeで開くことができる

### ISSUE THREAD

**Issue by ghost** [yasasii-team/Stepippo-iOS#10]

**Comment by riscait** [comment]
@red-hot-y 
Issue作成ありがとうございます！

**Comment by riscait** [comment]
当リポジトリをCloneしてXcodeで開けることを確認しました！
@YamaTatsu10969 さんはすでに完了されましたので、
@red-hot-y さんと @eyener3 さんがCloneしてXcodeで開くことができれば、
このチケットはCloseできます😊👍

**Comment by ghost** [comment]
clone後起動確認しました。

**Comment by eyener3** [comment]
clone後起動確認しました！

**Comment by riscait** [comment]
@stmtk1 向けにReoponします👌

**Comment by riscait** [comment]
@stmtk1 さんは完了されたようですね。
@Koki-Nakamura さんのタスクになります。

**Comment by Koki-Nakamura** [comment]
@Riscait 
Cloneしておきました！

**Comment by riscait** [comment]
@Koki-Nakamura ありがとうございます！
Closeしちゃいますね！
