### ISSUE TITLE
チェックボックスをどうするか考える

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#100]
### 必要性
・StackViewを進めるにあたりチェックボックスどうするか
・チェックボックスのライブラリを決めたが、そこから実装をどうするか止まっていたため再び考える

### 期待値
チェックボックスをどうするか決め、StackView・実装に入れるようにする。

### タスク内容
- ライブラリを決めたあと何をすべきか？
- チェックボックスを実装するには？
- チェックボックスにおいての疑問を解消する

### その他の情報
該当Issue #45

**Comment by eyener3** [comment]
おぉ、記念すべき100Issue..🎉✨

**Comment by riscait** [comment]
> おぉ、記念すべき100Issue..🎉✨

すごい！もう100なんですね！🎉🎉

**Comment by eyener3** [comment]
▼参考にしようと思っている記事
http://9ensan.com/blog/smartphone/iphone/iphone-uibutton-checkbox/

https://qiita.com/bohebohechan/items/49aa25ed9a24b04619a0

**Comment by riscait** [comment]
おぉ、カスタムクラスでの自作良さそうですね♪

**Comment by eyener3** [comment]
ありがとうございます！
カスタムクラスについてもまだ理解が及んでいないので
引き続き学んでいきたいと思います（*^･^*)♪
