### ISSUE TITLE
カスタムクラスについて理解する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#102]
### 必要性
チェックボタン実装において、カスタムクラスをする必要があるため

### 期待値
カスタムクラスについて理解し、実際に実装できること

### タスク内容
- カスタムクラスとは？
- 実装するには？
- 活用の仕方を知る

### その他の情報
カスタムviewと同義かなと推測。
（▼参考URL）

### 参考URL・画像など
https://qiita.com/maebaru/items/90f915f82e3d6425cbdc

**Comment by riscait** [comment]
いいですね！
カスタムビューはUIViewのカスタムクラス、
カスタムボタンはUIButtonのカスタムクラス

という感じで使ったりすると思います👌

**Comment by eyener3** [comment]
あ、カスタムボタン！💡
少しずつ理解が追いついてきましたっ
ありがとうございます^0^♪
