### ISSUE TITLE
[進捗画面] チェックボタンクラス専用のファイルを作成する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#103]
### 機能の必要性
- 別ファイルに切り分けることでViewControllerがすっきりする？

### その他の情報
別ファイルを作成することは必要なのだろうと思っているが、
まだハッキリ理解できていないため、やってみてから判断しよう..💡

▼関連Issue
#102 
#100 

### 参考URL・画像・スクリーンショット
https://swiswiswift.com/custom-button/

▼ググるコツが知りたくて見つけた記事です
https://swingroot.com/google-search/

**Comment by riscait** [comment]
別ファイルが必要ですね！原則、1class(or struct)につき1ファイル作ります👌

**Comment by eyener3** [comment]
ありがとうございます！
理解が深まりました☺️🙏💡
