### ISSUE TITLE
アクションシートについて考える

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#105]
### 必要性
アクションシートの実装に入るために理解を深める。

### 期待値
アクションシートの実装について理解でき、実装に移れること

### タスク内容
- アクションシートの実装方法
- storyboardへの配置方法

### その他の情報
▼以下の画像を目指す

### 参考URL・画像など
![スクリーンショット 2019-05-05 00 48 38](https://user-images.githubusercontent.com/45029154/57181526-e58cb400-6ecf-11e9-9ce9-71e063765b33.png)

**Comment by eyener3** [comment]
- UIAlertControllerのインスタンスを生成するらしいことはわかった

- アラートとの違いは、preferredStyleにUIAlertControllerStyle.actionSheetを指定するらしい

- アクションシートはstoryboardでは行なわず、コーディングのみで行なうようだ

▼参考資料
http://swift.hiros-dot.net/?cat=4&paged=2

https://iphone-tora.sakura.ne.jp/uiactionSheet.html

**Comment by riscait** [comment]
ちなみに、MiscVC.swiftのLine: 234~253 でもアクションシートを使っています👌

**Comment by eyener3** [comment]
ありがとうございます！
さっそく見てみようと思います^○^♪
