### ISSUE TITLE
アクションシート用のファイルを作成する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#106]
### 機能の必要性

- 期限変更にアクションシートを使用するため実装が必要となる

- 1classに1ファイルにするため

### 実装の期待値
エラーなく、アクションシートが表示される

### その他の情報
関連Issue #105

**Comment by riscait** [comment]
ActionSheetは今の所カスタムせずに標準のものを使うので新しいクラスを作る必要はないですね💡
使用するだけならファイルの作成は基本必要ないです。
新しくカスタマイズしたものを実装したいなら新しくクラスを作ります😊👌

もしくは、もっと簡単に使えるように（ショートカット的な）クラスを作ることはあります。

**Comment by eyener3** [comment]
> ActionSheetは今の所カスタムせずに標準のものを使うので新しいクラスを作る必要はないですね💡
> 使用するだけならファイルの作成は基本必要ないです。
> 新しくカスタマイズしたものを実装したいなら新しくクラスを作ります😊👌
> 
> もしくは、もっと簡単に使えるように（ショートカット的な）クラスを作ることはあります。

ありがとうございます！
龍之介さんのActionSheetがMiscVCにあったので
もしかしたら、そうなのかも💡と感じておりました☺️

ショートカット的なのもあるのですね！
あまりわかっていないので、
ググってみようかと思います^○^♪
