### ISSUE TITLE
ProgressBarについて考える

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#107]
### 必要性
ProgressBarの実装に入る前に把握すべきことを整理・理解する

### 期待値
整理・理解でき、ProgressBarの実装に入れること

### タスク内容
- ライブラリを使うかどうか..
- 実装方法 
- 再度、情報収集してみる

### その他の情報
関連Issue #45

**Comment by eyener3** [comment]
チェックボックス同様、期間や達成数を表す増減の画像が用意できれば、ProgressBarもオリジナルでもいけるのでは？と考えた💡

**Comment by riscait** [comment]
今の所最大で32段階（31日分）あるのでその分の画像を用意するのは現実的じゃなさそうですね🤔
達成度や進捗によって、表示する「幅:Width」を割合で変えていくのが一案かと思いました👌

**Comment by eyener3** [comment]
> 今の所最大で32段階（31日分）あるのでその分の画像を用意するのは現実的じゃなさそうですね🤔
> 達成度や進捗によって、表示する「幅:Width」を割合で変えていくのが一案かと思いました👌

たしかに、その懸念点も頭をよぎりました..😭🙏
コードで設定する形になるのでしょうかね
幅:widthの割合を変えていく実装について、
調べてみようと思いますっ😌！

**Comment by riscait** [comment]
ProgressBarは今まで使ったことなかったのですが、
ググってみたら、標準のUIProgressViewを使えば実装できそうかも？と思いました🤔
https://qiita.com/fromage-blanc/items/2ec7c89c3484765acf8f

色や太さ変えたり、画面を表示したら指定した割合まで進むように指定できそうですね💡

**Comment by eyener3** [comment]
リンクありがとうございます！
見てみました💡
標準でも良さそうですね♪

いまstoryboardにある標準progress barをそのままに
コードで指定する方向で行こうと思います^○^💡

**Comment by riscait** [comment]
はい！標準でダメそうだったり、もっと良いものにするのに必要だったら後々独自で作ってみましょう👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
はいっ、そのようにします！☺️🙏
