### ISSUE TITLE
ProgressBar用のファイルを作成する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#110]
### 機能の必要性

- ProgressBarの実装をするため

### 実装の期待値

- エラーなく、アニメーション（ゲージの増減）も実装できる

### 検討した実装案

- ファイル名は、ProgPBarVCにしようかな

### その他の情報

- 関連Issue #107

**Comment by riscait** [comment]
progress barのクラスを作成するってことですよね？☺️
ViewControllerじゃないと思うので、最後にVCは要らないかな👌

**Comment by eyener3** [comment]
レビューいただき、
ありがとうございます！
はい💡progress barのクラスを作成します♪

ViewControllerがいらないのですねっ
少しゴチャゴチャになっていました^-^
VCは消しておこうと思いますっ！

progress barの扱われ方について、
まだ理解が足りないようなので、もう少し掘り下げてみようと思います^-^💡

**Comment by eyener3** [comment]
ProgressBarがViewControllerに書かれている情報が多く、
なかなか何のクラスになるのか、どのテンプレートなのかたどり着けていませんでしたが
公式に「class UIProgressView : UIView」とあったので、これで考えていきたいと思います。
https://developer.apple.com/documentation/uikit/uiprogressview

**Comment by riscait** [comment]
UIKitのUIProgressViewを使うのであれば、とりあえずViewControllerに書けば良いと思いますよ👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> UIKitのUIProgressViewを使うのであれば、とりあえずViewControllerに書けば良いと思いますよ👌
> 
ありがとうございます！
そのようにしてみます^-^💡
