### ISSUE TITLE
ローカル通知が必要か、必要ならどこで必要かを議論する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#113]

**Comment by eyener3** [comment]
残り期限や完了していないタスクの通知もあるといいなと思いました^0^💡

**Comment by riscait** [comment]
その通知いいですね！
最初は、通知ボタン（🔔）用意しておいてオンかオフから切り替えられるだけで実装とか？🤔

**Comment by eyener3** [comment]
> その通知いいですね！
> 最初は、通知ボタン（🔔）用意しておいてオンかオフから切り替えられるだけで実装とか？🤔

任意で切り替えられるのいいですね^-^
よくToDoアプリでみかけるリマインダーみたいなものでしょうかね
それを一括でアリかナシかにするような。

完了できなかったタスクが一覧に戻りました、
みたいな通知もあるといいのでしょうかね

あとは、通知になるのか微妙ですが、
「合計〇〇回、挑戦をしました！」とか挑戦した回数の合計が見えるのもいいかもです^-^
