### ISSUE TITLE
【あいなー】SwiftLintを導入する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#114]
### 必要性
コーディングスタイルの静的解析をしてくれて、軽微な間違いは自動修正してくれる
※このIssueでは、導入と設定のみを行なう

### 期待値
問題なく、導入できること。

### タスク内容

- 別ブランチを最近のmasterから切って行なう

- 各プロパティ（デフォルト設定）の意味など調べる

### その他の情報
関連Issue #46 #47 

### 参考URL・画像など
https://qiita.com/uhooi/items/bf888b53b4b8210108aa

**Comment by riscait** [comment]
SwiftLintは全然わからないのですが、
ルールは後から追加するから、導入はしても実質動作は何も変わらない状態まで持っていくタスクという認識で合ってますか？😊

**Comment by eyener3** [comment]
> SwiftLintは全然わからないのですが、
> ルールは後から追加するから、導入はしても実質動作は何も変わらない状態まで持っていくタスクという認識で合ってますか？😊

はい！ルール選定のファイルを作る前段階まで進めようと考えました^-^💡
xcode設定も行なってみました🙇‍♀️
![スクリーンショット 2019-05-08 01 25 47](https://user-images.githubusercontent.com/45029154/57316287-66e28180-7130-11e9-82cb-7da1d1776701.png)
