### ISSUE TITLE
【あいなー】Carthageを使ってRealmライブラリを導入する 

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#116]
### その他の情報
関連Issue #24

**Comment by eyener3** [comment]
できる限りの事はやってみましたが、
エラーのままになってしまいます..><

明日に間に合わせようと思っていますが
難しかったら、申し訳ありません。。m(._.)m
![スクリーンショット 2019-05-07 17 31 50](https://user-images.githubusercontent.com/45029154/57285369-092d4580-70ee-11e9-97ca-a57ee53c5959.png)

![スクリーンショット 2019-05-07 17 27 39](https://user-images.githubusercontent.com/45029154/57285204-a9cf3580-70ed-11e9-81e0-f6a47bfb42e8.png)

![スクリーンショット 2019-05-07 17 29 20](https://user-images.githubusercontent.com/45029154/57285213-adfb5300-70ed-11e9-8761-37905bb3538c.png)

**Comment by riscait** [comment]
画像１枚目見てまず気になったのが、新しいブランチ切るとき、masterから切っていなそうに見えます🤔
新しいIssueに取り掛かるときは「最新のmaster」から切るようにしましょう！
方法は分かりますか？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
②あいなーさんがするべきなのはcarthage updateではなく、carthage bootstrapコマンドです。
carthageはすでにインストールされているようですし、cartfileもすでにプロジェクトに追加されています👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
#24 は誰か一人がやれば良いタスクで、僕が実施したので不要なタスクです。
あいなーさんに必要なのは#76 となります。
そして、#76 は新たにブランチを切る必要がないタスクです👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
画像2,３枚目で行なっているXcodeでのフレームワークの追加は、#24 など、誰か一人がやれば良いタスクなので #76 では必要ないです🙆‍♂️
もうすでにフレームワークあるので同じのが2つになってますよね？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます^-^！

やっている手順としては、
①Xcodeでカレントからmasterへチェックアウト
②masterからブランチを切る
③作業開始

今回の導入系のことは、
①Xcodeでカレントからmasterチェックアウト
②masterからブランチを切る
③ターミナルでgit branch をすると、Xcodeでのブランチが存在しないため、ターミナル上でも同じブランチを切ってから、導入を試みました。

#24 のIssueについては理解できました^-^
ゴチャゴチャになってしまっていて、
不要な作業をしていたようですね...><

#76 もブランチ不要なのですね💡
#76 のIssueをやってみようと思います🙆‍♀️

**Comment by eyener3** [comment]
こちらcloseしますね><💡

**Comment by riscait** [comment]
③がかなり怪しいですね…
同じブランチがないのはおかしいです。
もしかして、Xcodeとターミナルで別々のすてぴっぽプロジェクトを見てたりしませんか…？👀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> ③がかなり怪しいですね…
> 同じブランチがないのはおかしいです。
> もしかして、Xcodeとターミナルで別々のすてぴっぽプロジェクトを見てたりしませんか…？👀
> 
> Sent with [GitHawk](http://githawk.com)

③おかしいですよね..＞＜。
もう一度プロジェクトが正しいか、
確認してみようと思います🙇🏻‍♀️💡

**Comment by riscait** [comment]
ですね！それでダメなら…

プロジェクト削除→クローンし直し→carthage bootstrap
は試しましたか？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
```
mba:Stepippo-iOS katouayana$ git branch
  Add_ProgTabBarItem
  Add_Progstoryboard_UIParts
  Add_Progstoryboard_controller
  Add_Realm_to_Carthage
  Add_SwiftLint
  Add_progFile
* master
```

Xcodeの方ではなく、
Stepippoの方にありました^-^💡

**Comment by riscait** [comment]
ん？先にターミナルでブランチ切って、xcodeで見たら無かったということですか？🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> ん？先にターミナルでブランチ切って、xcodeで見たら無かったということですか？🤔
> 
> Sent with [GitHawk](http://githawk.com)

先にxcodeでブランチを切って、
ターミナルでの導入時にブランチを確認したら切ったブランチがなかった、
ということです^-^！

先日の再クローン以来、クローンはしていないですねっ
Finder上のスクショも貼りますねっ
![スクリーンショット 2019-05-07 19 24 43](https://user-images.githubusercontent.com/45029154/57292816-e145de00-70fd-11e9-9620-778e26d23854.png)
![スクリーンショット 2019-05-07 19 24 49](https://user-images.githubusercontent.com/45029154/57292828-e73bbf00-70fd-11e9-9f1d-d1fad0e1e9fe.png)

**Comment by riscait** [comment]
1枚目画像
ここにCartfileなどあるのはおかしいですね！

というかその前に一番上の画像をもう一度見てみたら、ターミナルの作業パスがStepippじゃなくてXcodeじゃないですか笑

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> 1枚目画像
> ここにCartfileなどあるのはおかしいですね！
> 
> というかその前に一番上の画像をもう一度見てみたら、ターミナルの作業パスがStepippじゃなくてXcodeじゃないですか笑
> 
> Sent with [GitHawk](http://githawk.com)

本来、Stepippoが作業パスでしたね^-^💡
混乱していたようです
もう大丈夫かと思われます^-^🙏
お騒がせいたしました><

**Comment by riscait** [comment]
![GitHawk Upload by Riscait](https://i.imgur.com/UknZ2Dy.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます..😿🙏

**Comment by riscait** [comment]
![GitHawk Upload by Riscait](https://i.imgur.com/uTWgFdj.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
それが原因で、エラーが消えなかったり、
コマンド打ってもエラーになっていたのですね><

すぐ混乱してしまいますね、、申し訳なかったです😿
次こそ、成功させたいと思います！

**Comment by riscait** [comment]
とんでもないです！原因がわかってよかった✨

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> とんでもないです！原因がわかってよかった✨
> 
> Sent with [GitHawk](http://githawk.com)

本当にありがとうございます。。（ ;  ; ）！！
