### ISSUE TITLE
[あいなー]Carthageのbootstrapコマンドでライブラリ環境を揃える

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#117]
### 必要性
ライブラリ環境を全員揃える

### タスク内容
`$ carthage bootstrap —platform iOS `コマンドを実行してライブラリをビルドする
 最新のmasterブランチで、エラーなくビルドできることを確認

### その他の情報
関連Issue #76  

### 参考URL・画像など
![スクリーンショット 2019-05-07 18 22 38](https://user-images.githubusercontent.com/45029154/57288782-1f8acf80-70f5-11e9-9707-7ec9cf9f8a71.png)

- エラー
No entry found for dependencies ios, —platform in Cartfile.resolved – please run `carthage update` if the dependency is contained in the project's Cartfile.（依存関係iosのエントリが見つかりません -  Cartfile.resolvedのプラットフォーム - 依存関係がプロジェクトのCartfileに含まれている場合は `carthage update`を実行してください。）

`carthage update`を実行しても変わらないため、調べてみる💡
（先日も同じエラーが出ていた。）

**Comment by eyener3** [comment]
Carthageが表示されました。
![スクリーンショット 2019-05-07 19 58 24](https://user-images.githubusercontent.com/45029154/57294389-7b0f8a00-7102-11e9-929c-ee978be1bbc7.png)
![スクリーンショット 2019-05-07 20 13 46](https://user-images.githubusercontent.com/45029154/57295136-cc207d80-7104-11e9-869e-47aac1f9eaaa.png)


▼同じエラーが出るのは変わらないので、再度調べてみる。
> No entry found for dependencies ios, —platform in Cartfile.resolved – please run carthage update if the dependency is contained in the project's Cartfile.（依存関係iosのエントリが見つかりません - Cartfile.resolvedのプラットフォーム - 依存関係がプロジェクトのCartfileに含まれている場合は carthage updateを実行してください。）

**Comment by riscait** [comment]
ん？bootstrapが成功したからcarthageフォルダができたのでは？

carthage updateをやったんですか？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
Xcodeでclean→buildを試しましたか？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> ん？bootstrapが成功したからcarthageフォルダができたのでは？
> 
> carthage updateをやったんですか？
> 
> Sent with [GitHawk](http://githawk.com)

成功したと思ったのに、エラーになるので、
どうしたらいいものかと思っていました^-^。

**Comment by eyener3** [comment]
> Xcodeでclean→buildを試しましたか？
> 
> Sent with [GitHawk](http://githawk.com)

やってみます^-^

**Comment by riscait** [comment]
> 成功したと思ったのに、エラーになるので、
> どうしたらいいものかと思っていました^-^。

>No entry found for dependencies ios, —platform in Cartfile.resolved – please run carthage update if the dependency is contained in the project's Cartfile.（依存関係iosのエントリが見つかりません - Cartfile.resolvedのプラットフォーム - 依存関係がプロジェクトのCartfileに含まれている場合は carthage updateを実行してください。）

上記のエラーってターミナルでコマンド打った時のエラーですよね？
なので、
> 成功したと思ったのに、エラーになるので、

の意味がちょっと理解できず🤔

ターミナルでやったならコマンド履歴が残っていると思うので、
最初からエラー出たところまでのスクショ貼ってほっしいです💡

**Comment by eyener3** [comment]
> ターミナルでやったならコマンド履歴が残っていると思うので、
> 最初からエラー出たところまでのスクショ貼ってほっしいです💡

またちょっと混乱してきました^-^
コマンド履歴は git log でしたよね🙇‍♀️？
現状、エラーの履歴の部分がなぜか出てこないので、
スクショ貼れず、ごめんなさい。。m(._.)m

もう少しやってみます^-^！

**Comment by riscait** [comment]
git logはコミットのログです！
ターミナルでどうコマンドを打った結果を見たいという意味です👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
やってみました！m(._.)m💡
![スクリーンショット 2019-05-08 01 39 36](https://user-images.githubusercontent.com/45029154/57317046-284dc680-7132-11e9-90a7-fdecfde9d951.png)

**Comment by riscait** [comment]
1回目(上手くいったかもの時)の履歴ですか？
違うのであれば1回目も同じ内容が表示されつつCarthageフォルダが出来上がった？🤔

Xcodeではどんなエラーが出てるんですか？
そちらをみたいです👀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> 違うのであれば1回目も同じ内容が表示されつつCarthageフォルダが出来上がった？🤔

↑こちらの通りですね^-^！

Xcodeのエラーはこちらです！
![スクリーンショット 2019-05-08 14 14 44](https://user-images.githubusercontent.com/45029154/57351168-cfb31380-719b-11e9-97d8-2f2b221d72d9.png)

うまく行ったかもの時に、
ずっと出ていたRealmのエラーは消えたのですが、
新しいエラーが出ました^-^。

**Comment by riscait** [comment]
エラーの内容は文面そのままなので分かりますね👍
できれば１回目のコマンド履歴が見たかったです👌

DerivedDataを削除してもう一度試してみてください！（ググると消し方は出てきます🙆‍♂️）

それでもダメならプロジェクト一度消して試してください👍←もう試しましたか？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
あ、CartfileとCartfile.resolvedファイルを見たいです👍
もしこれらを上書きしていたら上手くいかないと思うので…

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> エラーの内容は文面そのままなので分かりますね👍
> できれば１回目のコマンド履歴が見たかったです👌

historyコマンドで見ることができるようでやってみましたが、
打ったコマンドしか出ませんでした。
![スクリーンショット 2019-05-08 15 41 45](https://user-images.githubusercontent.com/45029154/57354909-cc258980-71a7-11e9-9013-54dfd7b05951.png)

> DerivedDataを削除してもう一度試してみてください！（ググると消し方は出てきます🙆‍♂️）
> それでもダメならプロジェクト一度消して試してください👍←もう試しましたか？

やってみます^-^


CartfileとCartfile.resolvedファイルのスクショ貼ります
![スクリーンショット 2019-05-08 15 36 15](https://user-images.githubusercontent.com/45029154/57355007-068f2680-71a8-11e9-950e-1c4490a3bdaf.png)

**Comment by riscait** [comment]
このCartfileは問題ないみたいですね👌
とりあえず、Carthageのインストールやuodateコマンド、Cartfileの作成・編集は不要ですのでクローンし直した時はやらずに、bootatrapのみで大丈夫です🙆‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございますっ^○^！

**Comment by eyener3** [comment]
再クローンし直してみます！💡

**Comment by riscait** [comment]
僕もクローンしてやってみました！
違いがあれば、比べてみましょう👌
<img width="837" alt="スクリーンショット 2019-05-08 21 51 45" src="https://user-images.githubusercontent.com/8737743/57376640-7e2a7900-71db-11e9-9bc0-3c16a914dec3.png">

**Comment by eyener3** [comment]
ありがとうございます(T ^ T)！！
