### ISSUE TITLE
[進捗画面] Storyboardに設置したUIパーツをVCのクラスに繋ぐ

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#123]
（やり方はいろいろあるけど）controlキー押しながらClass内部までドラッグする…

入門書にも書いてあると思います👌

ボタンを押した時など動作をコードで定義したいときは、IBAction

パーツの見た目（状態）をコードで操作したいときは、IBOutlet

を使います🙆‍♂️

viewDidLoadの上に定義しましょう👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
@Riscait 
ありがとうございます！
やってみます^0^！
