### ISSUE TITLE
タスク選択画面での画面遷移の実装

### ISSUE THREAD

**Issue by Koki-Nakamura** [yasasii-team/Stepippo-iOS#135]
### 必要性
各ボタン押下時の画面遷移を実装
### 期待値
各ボタン押下時の画面遷移を正常に実装出来ている
### タスク内容
- [ ] ×押下時の画面遷移
- [ ] Stock押下時の画面遷移
- [ ] Add押下時の画面遷移

### その他の情報
※「Stock」「Add」押下時の挙動を理解できていないため、次回MTG時に確認する

**Comment by riscait** [comment]
想定としては、
Stockボタン押下→Stock属性？をつけてRealmで記録、完了ダイアログ表示（遷移なし）
Addボタン押下→下部のStackViewに追加して表示させる処理（遷移なし）

あくまで僕個人のイメージなので、他にこうした方が良いんでは？などあれば皆さんも考えを教えていただければ💡

**Comment by Koki-Nakamura** [comment]
共有ありがとうございます。
どちらにせよ遷移は必要なさそうですね！
