### ISSUE TITLE
完了タスク・ストックタスク画面のFigmaで作成

### ISSUE THREAD

**Issue by yamatatsu10969** [yasasii-team/Stepippo-iOS#14]

**Comment by riscait** [comment]
>黄色っぽくしたのは、挑戦のイメージが黄色っぽかったからです！下のタブのアイコンは適当なので、気にしないでください！
悩んでいるところは、「最近達成、今年達成、それ以降」があるんですけど、そこの色をどうしたらいいかな〜となっています。

Figma見ました！すぐ実装できそうな出来栄えですね✨
ちなみに、TableViewのsection header が太字で中央寄せなのは意図して配置していますか？😊

**Comment by riscait** [comment]
>左寄せよりも見やすいかなと思って配置しました！左寄せでも構わないんですけどね:普通の顔:

@YamaTatsu10969 なるほど！承知しました👌一度実装してみましょう☺️
