### ISSUE TITLE
進捗画面のStackViewにAutoLayoutの制約をつける

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#141]
### 機能の必要性
デバイスに関係なく意図した位置にパーツが配置されるため

### 実装の期待値
iPhoneSE ~ XS Maxどれで確認しても各パーツが途切れず、崩れることなく表示されること

### 検討した実装案
1. StackViewに上、横の制約をつける
2. SEで収まらなそうなら、ScrollViewをUIViewとStackViewの間に入れて、
ScrollViewの上に全てのパーツが載っている状態にしてスクロール可能にする

### その他の情報
ScrollViewはコツを掴むまでは難しい…

### 参考URL・画像・スクリーンショット
ScrollViewなくてもいけそう！
<img width="1645" alt="スクリーンショット 2019-05-14 23 12 52" src="https://user-images.githubusercontent.com/8737743/57704952-dd85fe80-769d-11e9-9f4d-9f170f3a6731.png">

**Comment by eyener3** [comment]
@Riscait 
龍之介さん、ありがとうございます..＞＜！
ずっと取り組んでいましたが、なかなか苦戦しています^0^;
同じようにできるようにやってみます^-^🙏
