### ISSUE TITLE
チェックボックス用のカスタムクラスの中身を実装する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#143]
- Controllersフォルダの中にあるので、Viewsフォルダに移す
- チェックされている状態とチェック前の状態の画像を設定する
チェックボックスが押された時の挙動を設定する
など

検索すれば実装方法が丸々のってる記事があるので、基本その通りにすれば動くと思う

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます^-^
進めていけるようにやってみます😊💡

**Comment by riscait** [comment]
はい！焦らず1Issueずつ順番にやっていきましょう☺️👍

**Comment by eyener3** [comment]
> はい！焦らず1Issueずつ順番にやっていきましょう☺️👍

はい^-^！
本当にありがとうございます😿🙏✨
