### ISSUE TITLE
CocoaPods 1.7.0へのアップデートと動作確認

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#148]
CocoaPods1.7.0へアップデートし、問題なくアプリをビルドできることを確認する

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
こちら、やってみようかなと思ったのですが、
アップデートしてビルドエラーがなければ出来たことになるのでしょうか？^-^
podfileは、このようになっています..💡
![スクリーンショット 2019-06-01 03 10 32](https://user-images.githubusercontent.com/45029154/58725756-e7885b00-841a-11e9-8278-e3f834e117f4.png)
![スクリーンショット 2019-06-01 03 18 57](https://user-images.githubusercontent.com/45029154/58726180-04715e00-841c-11e9-9646-7396f86ee12b.png)

**Comment by Sab-swiftlin** [comment]
CocoaPodsって使ってるんでしたっけ？？

**Comment by riscait** [comment]
> CocoaPodsって使ってるんでしたっけ？？

すみません、このプロジェクトでは使ってないですね…！
完全に脊髄反射でIssue作成していました。。

@eyener3 
対応ありがとうございます！🙏
アップデート自体はしておいた方が良いことだとは思いますが、お手を煩わせてしまいました🙇‍♂️

このIssueはCloseします🙇‍♂️
