### ISSUE TITLE
[XD] その他画面の画面定義書を作成する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#15]
# XD制作進捗
![4/3進捗 by Riscait](https://i.imgur.com/fHeUfc7.jpg)

**Comment by eyener3** [comment]
@Riscait
龍之介さん、
もう実装入っていますか？^-^💡

**Comment by riscait** [comment]
@eyener3 
僕はまだ実装入っていないです😊
それぞれ画面定義書が自分なりにもうOKと判断できる方は実装入っていきましょうか？

**Comment by riscait** [comment]
あ、In Progress にしていなかった！
カンバン上で、In Progressにしました👍

**Comment by eyener3** [comment]
@Riscait
前回のMTGの時に、
ちょこっと実装入れる人は入る感じにしましょうか、とお話ししていた気がします^-^！
わたしはどちらでも大丈夫ですっ♪

**Comment by riscait** [comment]
@yasasii-team/ios 
そうですね！早いに越したことはないので、入れる方は入っちゃいましょう😊
実装入るにあたって、
順序を整理する＆周りから進捗が見やすくするためにも各員でIssueを作りましょうか？
例: （担当画面の）storyboardとそれに対応するUIViewControllerファイルを作成する
（実装は別Issueで行う）
みたいな感じで、細かく分けて😊👍
