### ISSUE TITLE
[進捗画面]チェックボタンのアニメーション

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#156]
### 機能の必要性

- 今のままのチェックボックスだと少しなんかさみしい感じがするから

### 実装の期待値

- チェックボタンを押す楽しみ、みたいなユーザー体験を作りたい

### 検討した実装案

- この動画のようなボタンにしたい

https://www.youtube.com/watch?v=S6q5d3RvVY8

（8:30あたりのアニメーション）

### その他の情報

- ボタンのImageを別のモノに変更する可能性あり

**Comment by eyener3** [comment]
カラーを変えてみましたが、
設定が間違えているようなので修正いたします(＞人＜;)

[![Image from Gyazo](https://i.gyazo.com/b2ccdb294425a1a9883125cf06ef29b7.gif)](https://gyazo.com/b2ccdb294425a1a9883125cf06ef29b7)

二つ目のチェックボタンを押すと、
Xcodeに飛んで、エラー文になりました
龍之介さんのファイルでなっていました＞＜
![スクリーンショット 2019-05-25 22 49 55](https://user-images.githubusercontent.com/45029154/58370504-53158880-7f42-11e9-9169-66c01a73017b.png)


![スクリーンショット 2019-05-25 22 57 45](https://user-images.githubusercontent.com/45029154/58370533-c1f2e180-7f42-11e9-89f2-d4547b6fd1b2.png)

connectionをつなぎ直して、もう一度やってみます^0^

**Comment by riscait** [comment]
@eyener3 
インデント（字下げ）を見るとわかるのですが、閉じ括弧が足りないのでエラーが出てきたんだと思いますよ👌
この状態だと、checkClicked1の中にcheckClicked2と3、それにviewDidLoadまでもが入っている状態になっていますよね？

括弧にカーソルを合わせると対応した（閉じ・または開き）括弧が光るのでかぞえてみましょう👍
括弧は開いたら閉じる！に要注意です💡

**Comment by eyener3** [comment]
@Riscait 
龍之介さん、原因究明しながら触ってみたら、
無事、エラー解決しましたー^0^！！
![スクリーンショット 2019-05-25 23 48 44](https://user-images.githubusercontent.com/45029154/58370963-ab9b5480-7f47-11e9-8910-e118731ab0b0.png)

**Comment by eyener3** [comment]
ここまで進みました^-^
オレンジと青の枠を消して、タップした後のボタンに色をつけたいなと思います＞＜
[![Image from Gyazo](https://i.gyazo.com/63a65371f81b7096d1c21898dcfdad5f.gif)](https://gyazo.com/63a65371f81b7096d1c21898dcfdad5f)

**Comment by riscait** [comment]
すごい、動きと色がつくと面白いですね♪

**Comment by eyener3** [comment]
> すごい、動きと色がつくと面白いですね♪

はい、わくわくします(*´∀`)♪
