### ISSUE TITLE
【XD】進捗画面の画面定義書を作成する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#16]
残期間と残タスクを確認できるメイン画面

**Comment by eyener3** [comment]
![スクリーンショット 2019-04-04 19 22 14](https://user-images.githubusercontent.com/45029154/55548800-4a0cf580-570f-11e9-81d2-4a1a98247537.png)

1. UI設計
MoneyFowardのUIを参考にしようかと。
※インジケーターが円グラフだったので模索中..
- 配色や画面遷移がすごく参考になる

2.配色・フォント
- 3色
   - 背景：白、メイン：緑or青系、差し色：赤かオレンジ
- フォント：まるくやわらい感じのを選ぶ

3.インジケーター
- ライブラリを少しアレンジして独自性を出す

4.ボタン 
- チェック
- キャンセル
- 期間変更
   - 毎日
   - 毎週
   - 毎月
- タスク変更

[Project](https://github.com/yasasii-team/Stepippo-iOS/projects/3)

**Comment by riscait** [comment]
おお、すごい！Projectsのnote機能活用されてますね！
あいなーさんの采配で、Issueとして作ってくれてしまっても大丈夫ですからね🙆‍♂️
配色などなど楽しみです✨

**Comment by eyener3** [comment]
ありがとうございます^0^！
Issueを作るとなると、
わたし専用のものとして、になる感じですか？🙆‍♀️

**Comment by riscait** [comment]
専用といえば専用ですね👍
アサイニーをあいなーさんにしていただければ大丈夫です🙆‍♂️

**Comment by eyener3** [comment]
承知しましたっ😊
ありがとうございます！^○^♪

**Comment by eyener3** [comment]
以下、修正いたしました^-^！
- インジケーター
- テキスト
- フォント

https://xd.adobe.com/view/4a8c1654-681b-4ef3-59fb-130e4eeb3ed8-3cbd/

**Comment by riscait** [comment]
おぉ、ボタンの囲みがついて分かりやすくなりましたね✨
インジケーターの修正もありがとうございます！

期間と残数のインジケーターの色が違う方が分かりやすいかもと思いました☺️
あと達成済みタスクは文字色をグレーにするのはどうでしょう？💡

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
@Riscait
承知しました^-^

**Comment by eyener3** [comment]
> 期間と残数のインジケーターの色が違う方が分かりやすいかもと思いました☺️
あと達成済みタスクは文字色をグレーにするのはどうでしょう？💡

修正いたしましたっ
https://xd.adobe.com/view/4a8c1654-681b-4ef3-59fb-130e4eeb3ed8-3cbd/

**Comment by riscait** [comment]
@eyener3 
おぉっ色が分かれてさらに良いですね✨☺️

細切れですみません…！
残り期間のラベルは「残り〜%」ではなく「残り何日」と表示した方が分かりやすいと思いました💡
最終日は「今日まで」とか表示できたらなお良いですね🧐
もし、「残り〜%」と表示させるとしたらインジケーターにかぶせて表示するとそれっぽいかも？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
承知しました
ありがとうございます^-^

**Comment by eyener3** [comment]
修正しました💡
https://xd.adobe.com/view/a954a8e0-41be-4553-44e3-d2bd4d147e2d-df65/

**Comment by riscait** [comment]
@eyener3 
ありがとうございます！早い！
ドメインを契約できるようになってる✨良いですね🎉

**Comment by eyener3** [comment]
@Riscait
ありがとうございます^-^
ドメイン契約ができるようになってるというのは、どこで判断できるのでしょうか？🤔💡

**Comment by riscait** [comment]
@eyener3 
「ドメインを契約する」のチェックボタンが押せるようになってる！という意味です^^b
何もないところを押すと青く光って教えてくれます💡

**Comment by eyener3** [comment]
@Riscait
理解できましたっ☺️🙏

**Comment by eyener3** [comment]
ここのIssueのCloseのタイミングがあれば教えていただきたいです！🙇🏻‍♀️

**Comment by riscait** [comment]
今回は、各々自分でもう良いと思ったタイミングで実装入ることにしましょうか？
途中でまたこのIssueでの議論や実装が必要になったらReopon（復活）させることにして、Closeしちゃいましょうか😊

**Comment by eyener3** [comment]
@eyener3
Close,Reoponについて
承知いたしましたっ

実装どうしたらいいでしょうかね
次回のMTG後からでも
ぜんぜんOKですっ^-^

**Comment by riscait** [comment]
画面定義書終わった方は実装入った方がいいかと思います👌😊
もしくは、その他のIssueをやるか💡

**Comment by eyener3** [comment]
承知しました^-^！
それは、一旦ここはCloseします^^💡
