### ISSUE TITLE
IPPOモデルでプライマリーを設定する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#160]
### バグの概要
#147 
プライマリキーに設定するためのidプロパティは用意してあったが、
idをプライマリキーとして登録するためのメソッドが不足していたため、プライマリキーがない状態となっていた
（レビュー漏れでした！）

### 本来の期待動作
IPPOにプライマリキーとしての"id"が存在すること
RealmObjectAccesible のめメソッドを使ってwriteできること

### 参考スクリーンショット・画像・動画・URL
https://realm.io/docs/swift/latest#primary-keys
```swift
    override static func primaryKey() -> String? {
        return "id"
    }
```

**Comment by naipaka** [comment]
すみません。。。

> RealmObjectAccesible のめメソッドを使ってwriteできること

をどう実現したらいいかがわかりません！

プロトコルのメソッドの使い方がまだわかっていません。。すみません🙇‍♂️
インスタンス化してメソッドを呼び出すものだと思っていました。。

**Comment by riscait** [comment]
@naipaka 
こんな感じで、class定義かextensionで: の後に書けば使えるようになります🙆‍♂️！
https://github.com/yasasii-team/Stepippo-iOS/pull/154#issuecomment-495931417

**Comment by naipaka** [comment]
いつもリプライが早くて助かります😭
試してみます！

**Comment by naipaka** [comment]
確認できました！
![image](https://user-images.githubusercontent.com/45661924/58485085-53aa5b00-819e-11e9-987a-67e40a612863.png)

**Comment by riscait** [comment]
おぉ良かった✨
