### ISSUE TITLE
その他画面のTypo修正

### ISSUE THREAD

**Issue by Sab-swiftlin** [yasasii-team/Stepippo-iOS#164]
### バグの概要
その他画面の最下部にある開発者の情報表示にTypoがありそうなので、修正する

### 再現方法
1.アプリを起動
2.その他画面に遷移

### 本来の期待動作
`Stepippo（v1.0.0）Developed by やさしい会 iOSチーム` と表示される

### その他
誤解でしたらクローズお願いします。

### 参考スクリーンショット・画像・動画・URL
![Simulator Screen Shot - iPhone Xʀ - 2019-05-26 at 22 33 09](https://user-images.githubusercontent.com/50907353/58382575-f8923000-8006-11e9-8c86-fe7d7b43634a.png)

**Comment by riscait** [comment]
ほんとだ！すてっぴぽになってますね！

**Comment by Sab-swiftlin** [comment]
お手軽Issueなので、どなたかにサクッとFIXして頂けそうですね！
