### ISSUE TITLE
ストック済みIPPOリスト画面のセクション分け

### ISSUE THREAD

**Issue by Sab-swiftlin** [yasasii-team/Stepippo-iOS#167]
### 機能の必要性
ストック済みIPPOリスト画面の表示にセクション分けが必要か、必要ならどうグルーピングするかを検討したいです。
皆様ご意見お願い致します。
既に決まっている内容がありましたらそちらもご教示いただけますと助かります。
よろしくお願い致します。

### 参考URL・画像・スクリーンショット
![Simulator Screen Shot - iPhone Xʀ - 2019-05-25 at 23 57 05](https://user-images.githubusercontent.com/50907353/58384694-bde8c180-801f-11e9-98d1-ee4cf31bb672.png)

**Comment by eyener3** [comment]
セクションわけ、あった方がタスク管理しやすくなるでしょうかね..🤔💡
分けるとしたら、時期（日時？）とかジャンルとかでしょうか..
特に決まっていなかったのと、画面担当者が作りたい感じで進めてもいいということになっているので、こうだといいなぁと思う感じでいいような気もします^0^！

**Comment by Sab-swiftlin** [comment]
ありがとうございます！
なるほど、結構自由度高いんですね！
では現状は特にセクション分けせず、ストックしたのが新しいものから古いものの順で並ぶようにしておこうと思います。
