### ISSUE TITLE
進捗画面: 残り日数をLabelに表示する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#176]
### 機能の必要性

- 保存されたデータに基づき、ユーザーが視覚的情報を得られるようにする

### 実装の期待値

- ユーザーが設定した期間に基づき、「残り〇〇日」のLabelに反映される
![Screen Shot 0001-06-06 at 3 14 37 AM](https://user-images.githubusercontent.com/45029154/58985871-3ff29a80-8817-11e9-916e-0fe271391246.png)

**Comment by eyener3** [comment]
うまくIssueのタイトルがつけられるようになりたいものです..(T . T)
このあと、達成数のLabel、ProgressBar（期間・達成数）の2つもIssueを立てる予定ですが、
Labelという括りで「残り日数」「達成数」を1つのIssueにまとめるべきでしょうか(＞人＜;)..

**Comment by riscait** [comment]
タイトル難しいですよね〜(＞＜)
実装する内容は違うので、別々のissueで良いかと思います！
その方が実装もレビューもしやすそう💡

**Comment by eyener3** [comment]
> タイトル難しいですよね〜(＞＜)
> 実装する内容は違うので、別々のissueで良いかと思います！
> その方が実装もレビューもしやすそう💡

ありがとうございます！
Issue、分けますね^-^💡
タイトルについて、「もっとこう表現した方が理解しやすいかも！」などありましたら、
ぜひ、助言いただけると有難いです..(＞人＜;)

**Comment by riscait** [comment]
承知しました(๑•̀ㅂ•́)و✧

なんと表示するのか先に決めておいた方が実装とレビューしやすいかもですね👌
期間設定が毎日の時→現在時刻と〇〇との日付差分を計算して「残り△時間」と表示
    例: 今21時なら、24時まで残り3時間なので、「残り3時間」と表示する
毎週の時→
毎月の時→
みたいな🤔

**Comment by eyener3** [comment]
@Riscait 
ありがとうございます^-^
例のところがタイトルになるイメージなのでしょうか？
１つのIsseuで、毎日、毎週、毎月の3つに対する、差分計算と表示を実装することになるのでしょうか？^-^

**Comment by riscait** [comment]
> @Riscait
> ありがとうございます^-^
> 例のところがタイトルになるイメージなのでしょうか？
> １つのIsseuで、毎日、毎週、毎月の3つに対する、差分計算と表示を実装することになるのでしょうか？^-^

どちらでも大丈夫ですが、1つのIssueで良いかと思います🙆‍♂️

**Comment by eyener3** [comment]
@Riscait
ありがとうございます(*´∀`)
