### ISSUE TITLE
進捗画面: 達成数をLabelに表示する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#180]
### 機能の必要性
達成数の進捗を可視化する

### 実装の期待値
RealmでIPPOを取得して表示させる

### 検討した実装案
0/0, 
0/1, 1/1,
0/2, 1/2, 2/2,
0/3, 1/3, 2/3, 3/3
⬆︎上記、10パターンの表示を目指す💡

### その他の情報
機能の提案に関するその他の情報

### 参考URL・画像・スクリーンショット
![Screen Shot 0001-06-16 at 9 06 53 PM](https://user-images.githubusercontent.com/45029154/59579285-1aaf3780-9107-11e9-9181-2642a3b0d7d8.png)

**Comment by riscait** [comment]
4つのIssueの中でこれが一番簡単そうですね😊

**Comment by eyener3** [comment]
ありがとうございます^-^💡
