### ISSUE TITLE
[タスク選択画面]後でやるボタンでIPPOを後でやるIPPOとして登録する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#186]
### 機能の必要性
その機能がなぜ必要なのかの明確で簡潔な説明

### 実装の期待値
後でやるIPPOとしてRealmでDBに登録でき、StockedIPPOVCで確認できる

**Comment by Koki-Nakamura** [comment]
すみません、このタスクの意味がわかりません。
ご都合の良いタイミングで共有して頂けませんか？

**Comment by riscait** [comment]
Addボタン隣のボタンでタスクのステータス（進捗状況）を「後でやる」にして保存します。

**Comment by Koki-Nakamura** [comment]
ああ〜なるほど！w
StockボタンでStockするということですね！
ありがとうございます。

**Comment by riscait** [comment]
はい！「Stockという呼び方がわかりにくい」と判明してからはなるべく使わないようにしてたので伝わりづらくなっちゃいましたね🙇‍♂️
