### ISSUE TITLE
UserDefaultsで保存する基準の曜日をStringで保存していたがIntにする

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#187]
あまりよく考えずにとりあえず「月曜日」などと文字列で保存してしまっていたのですが、
やはり、言語に依らないIntで保存しないと使うときに面倒だなと思いました😢

Sunday = 1
Monday = 2
...のようにIntに変えようかと思うのですがどうでしょうか？

**Comment by riscait** [comment]
@Sab-swiftlin 
すでに実装しているSabさんの所にも影響出てしまうのですがいかがでしょう？🙇‍♂️

**Comment by Sab-swiftlin** [comment]
#162 でもそこは変更しようと思っていたところなので問題ありません！
