### ISSUE TITLE
新機能案のリストアップ、気軽にみんなでコメント♪

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#19]
新機能の案が思いついたら、コメントで気軽に書き残していきましょう！
そして、v1.0.0リリース後、**次のアップデートではどの機能を入れようかー？**
とここを見て決められたらいいなと思っています👌

- [ ] 残りの挑戦数だけ、アプリアイコンにバッジを表示する機能
- [ ] ウィジェットに挑戦を表示する機能
- [ ] 残り挑戦数を通知する、ローカル通知機能
- [ ] 挑戦の記録として写真や動画投稿ができる
- [ ] 簡単なRPG要素（LevelUp）があると楽しそう
- [ ] シェアできる
- [ ] 同じジャンルの挑戦をしている人たちでグループが作れる
- [ ] iPadへの対応
- [ ] 横持ち(Landscape)への対応
- [ ] ユーザー登録（SNS認証？）
- [ ] 操作のチュートリアル（必要であれば..）
- [ ] スプラッシュ画面（アプリ立ち上げ時の画面）

**Comment by riscait** [comment]
- 残りの挑戦数だけ、アプリアイコンにバッジを表示する機能
- ウィジェットに挑戦を表示する機能
- 残り挑戦数を通知する、ローカル通知機能

を思いつきました😊

**Comment by eyener3** [comment]
・挑戦の記録として写真や動画投稿ができる
・簡単なRPG要素（LevelUp）があると楽しそう
・シェアできたり、同じジャンルの挑戦をしている人たちでグループが作れる仕組みがあるとモチベになりそう

挑戦を継続することで自信にも繋がると思っているので、仲間やコミュニティの存在や自分以外へのアウトプット要素があるといいなと。

Studypulsや、みんチャレというアプリが好きで、その二つの仕組みは継続面でもいいなと感じますね^-^

難易度にもよると思いますので、
必ず次回のアップデートで、
というわけではないです^-^☀︎

**Comment by riscait** [comment]
・iPadへの対応
・横持ち(Landscape)への対応

優先度は低めですが、ゆくゆくはどんな比率の画面でも対応できるアプリにしたいですね✨

**Comment by eyener3** [comment]
> ・iPadへの対応
> ・横持ち(Landscape)への対応
> 
> 優先度は低めですが、ゆくゆくはどんな比率の画面でも対応できるアプリにしたいですね✨

Universal化、いいですねっ💡

**Comment by eyener3** [comment]
- ユーザー登録（SNS認証？）
- 操作のチュートリアル（必要であれば..）
- スプラッシュ画面（アプリ立ち上げ時の画面）

その他
- アプリのアイコンやロゴ

**Comment by riscait** [comment]
アプリアイコンとスプラッシュはv.1.0.0に必要ですね！issue作っちゃいましょうか👌

操作のチュートリアルも必要そうなら早めに入れたいですね(๑•̀ㅂ•́)و✧

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
