### ISSUE TITLE
後でやる（Stock）からIPPOを削除出来るようにする

### ISSUE THREAD

**Issue by minmin0530** [yasasii-team/Stepippo-iOS#203]
### 機能の必要性
IPPOがStockに溜まり過ぎて邪魔にならないようにするため

### 実装の期待値
IPPOがStockから削除され、Realmからも削除される

**Comment by Sab-swiftlin** [comment]
この機能は既に実装済みかと思います！

**Comment by minmin0530** [comment]
タスク選択画面からは削除できますが、タスク一覧画面のStockからは削除できない状態です。
なので、このIssueを立てました。
@Sab-swiftlin

**Comment by Sab-swiftlin** [comment]
なるほど！
実はStockedIPPOVCでは左にスワイプで削除ボタンが出るように実装されているのですが、ListedIPPOVCにスワイプアクション持ってかれちゃってますね。
そこの修正をする感じになりそうですね！
ありがとうございます！

**Comment by riscait** [comment]
なるほど、気がつかなかった！
