### ISSUE TITLE
[Realm]挑戦を記録、読み込むプロトコルを作成する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#26]
### 必要性
専用のプロトコルを作り、抽象化しておくことで以下のメリットがあります。

1. `import RealmSwift` する（依存する）クラスを減らすことができる
2. 今後、もしDBをRealmから他のサービスに乗り換えたとしても、専用プロトコルだけを書き換えれば良い（専用プロトコルをつくらないと、DBの読み書きを行なっている場所すべてで書き換えが必要

### プロトコル案
`BrandNewTryWriter`: 挑戦をDBに書き込むプロトコル
`BrandNewTryReader`: 挑戦をDBから読み込むプロトコル

### 参考URL・画像など
「挑戦」を英語でいうとChallenge? Try?
https://ameblo.jp/eibunpo/entry-11427563971.html
「新しい」の英語の言い方
http://upgradeourenglish.com/speaking/new-expressions/

**Comment by eyener3** [comment]
@Riscait
ありがとうございます^-^！

挑戦について、
Tryの方が意味としては
マッチしている感じですね^-^♪

新しいの英語の言い方も色々あるのですね💡
個人的に好きなのは、Updateという言葉が好きで、表現として、TryをUpdateする！みたい感じもいいなと思いました^-^

他の方の意見も聞いてみたいですね☺️

**Comment by riscait** [comment]
@eyener3 
ありがとうございます！✨

そうなんです、一応調べたらTryの方が英語的に合っている上に短いので良さそうです👍

Updateだと、`TryUpdateWriter` もしくは`UpdateTryWriter` って感じですかね？💡

意見たくさん聞きたいですね！
どんどん議論していきましょう😊

**Comment by eyener3** [comment]
すみません..><
ちょっと思い違いをしていたようでした^-^
管理者側の視点のお話だったのですね💡
Reaml,DB,プロトコルについて、まだあまり理解が深くないので
少し調べたりしてみて、またすぐに書き込みたいと思います^-^！

**Comment by eyener3** [comment]
Realmについて調べていたら、
公式サイトを見つけました^-^
こちらを使って作成していくのでしょうか^-^
https://realm.io/

**Comment by riscait** [comment]
@eyener3 
僕たち側の話ですが、「挑戦」を英語で言うと…ということなので間違ってはいないかと(๑•̀ㅂ•́)و✧

肝心の公式サイト忘れてました！ありがとうございます😊
ドキュメントが丁寧に書かれているのでまた主にそちらを参考にしていくと思います💡
（日本語ドキュメントはちょっと古いから、最新版の英語情報と見比べながら）
プロトコルについては僕もやっと分かってきた、というくらい今まであまり使ってこなかったので僕も勉強しながらです(>_<)b

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
