### ISSUE TITLE
進捗画面のstoryboardとそれに対応するUIViewControllerファイルを作成する （実装は別Issueで行う）

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#30]
### 必要性
実装の事前準備として。
### 期待値

- Views
  - Prog.storyboard
  - 

- Controller 
  - ProgVC.swift
  - 

### タスク内容
- 上記4つのファイル作成

### その他の情報
Prog = Progress screen（進捗画面）という意味。

**Comment by eyener3** [comment]
これでcommitしてみます！
間違いがあったら、ごめんなさい..><
![スクリーンショット 2019-05-02 12 59 53](https://user-images.githubusercontent.com/45029154/57056873-363dba80-6ce0-11e9-895e-973f67905373.png)

**Comment by riscait** [comment]
問題なさそうにみえます！
