### ISSUE TITLE
Swift 5 に対応（必要があれば既存コードの変換も）する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#31]
### 必要性

- 最新のSwiftを使いたい
- 早めにやっておいた方が影響ファイルが少なくて楽
- Swift Conversion という警告⚠️が出てしまっている

### 期待値

1. 警告文の「Conversion to Swoft 5 is available」を押して、Convert（変換）する
2. 変換した後に、警告・エラーが出ていない

**Comment by eyener3** [comment]
行なってみました^-^
「現在のswift構文への変換に失敗しました
移行を試みる前に、選択されたすべてのターゲットが現在構成されているSwiftバージョンで正常にビルドされることを確認してください。」
というようなエラーが出てしまいました。
解決できるようにやってみます
https://swift.org/migration-guide-swift5/

**Comment by riscait** [comment]
ありがとうございます！
@eyener3 アサインしておきました👌

試しにですが、僕のブランチでやってみたところ、「変換は必要ありません、続けますか？」的な正常メッセージが出ました。

Info.plistは繋ぎました？
何か環境が違うのかもしれませんね…🤔
（その他画面追加用ブランチで試したのであまり参考にならないですね💦）

参考URLありがとうございます！
Google翻訳して読まねば(๑•̀ㅂ•́)و

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます^-^
エラー文をググると、『Steppipo/Info.plistになってるよ！存在しないよ！』という感じなので、Resouceに繋がっていないのが原因かもです..

XcodeやFinder上ではResouceに繋がっているように表示されていますが..><
念のためXcodeのバージョンも確認しました。

対処法を調べているのですが、
なかなか解決に至らずで..🙇🏻‍♀️💦

（ちなみに、この作業は一人一人が行なうissueになるのでしょうか？^-^）

**Comment by riscait** [comment]
@eyener3 
お、やはり！
Xcodeで、Targetを開き、アプリ名とかバージョンとかを変えられるところを…

とここまで書き気がついたんですが、そのリンクは僕が #29 で直しましたよね？

先程マスターにマージしたのでpullすれば反映されているかと思いますよ👌

（おそらく一人がやれば良いタスクかと思います👍）

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
承知いたしました^-^

**Comment by eyener3** [comment]
@Riscait 
アサインを龍之介さんに渡しました^0^

**Comment by eyener3** [comment]
最新のSwift5には設定できました。

一つだけ、教えていただきたいです><
こちらのエラーって、
皆さんも出ているのでしょうか？
![スクリーンショット 2019-04-08 17 01 17](https://user-images.githubusercontent.com/45029154/55708280-7d59c800-5a20-11e9-9271-a6742e565eef.png)

**Comment by riscait** [comment]
@eyener3 
Info.plist修正前は出ていたような気がします！

どのブランチで作業していますか？🧐
最新のmasterブランチであれば多分出ないと思います😊👍

@YamaTatsu10969 
やまたつさんの環境ではどうでしょう？？

**Comment by eyener3** [comment]
もう一度やってみます^^

**Comment by eyener3** [comment]
色々と調べてやってみたところ
無事、解決できました^-^

**Comment by riscait** [comment]
@eyener3 
おぉ、すごい！✨
プルリクエスト作成お待ちしています☺️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます^-^
これもブランチ切る〜pushまでの流れになるのでしょうか？^-^

**Comment by riscait** [comment]
そうです👌
作業するときは、
①masterをcheckoutする（masterでは作業したりコミットしない）
②git pullして最新にする
③作業ブランチを切る
がお決まりの流れになります👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
理解できましたっ
ありがとうございます😊！
