### ISSUE TITLE
ページ切り替え用ライブラリの選定

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#32]
### 必要性
マネーフォワードなどのスワイプしてVC内ページを切り替えるライブラリは何種類も存在する
どのライブラリが使いやすいか、優れているかをザッと比較して、すてぴっぽで使うライブラリを決定する

### 期待値
該当ライブラリを列挙し、優劣を挙げて比較する

### タスク内容
- [ ] 該当ライブラリを列挙する
- [ ] それぞれの利点・デメリットをまとめる
- [ ] 比較して、採用するライブラリを決定する

### その他の情報
ライブラリ管理にはできればCarthage、次点でCocoaPodsを使いたいと考えています。

**Comment by yamatatsu10969** [comment]
## 参照
https://qiita.com/jun1009/items/14ca3cc0ed458ff54bb1#yukiasaigecco-1727
https://qiita.com/susieyy/items/1f28531a1c58d9158896
https://qiita.com/0905Tom/items/3e305a2bd2bc57c663fa
http://animane.hatenablog.com/entry/2016/03/22/161644

**Comment by riscait** [comment]
すごい！まとめ記事いいですね♪
今一番上の見てますが、個人開発アプリに入れたいのがたくさん、、🤤

**Comment by yamatatsu10969** [comment]
# 該当ライブラリ
## xmartlabs/XLPagerTabStrip
**メリット**
日本語の参考資料がたくさんある。
表示方法が多数ある。通常のタブ、バーのみ、Twitter風、Segmentedなど。
既存のUIViewControllerを利用するため、Swiftのversion upの影響が少なそう（予測）

**デメリット**
特に見当たらない

## PageMenu
**メリット・デメリット**
ほぼXLPagerTabStripと変わらないくらい性能良さげ。

## ParallaxEffect
**メリット**
画面の切り替え時にはとても便利そう
**デメリット**
記事があまりない。
タブの切り替えには向いていない。
画面全体をペーシングするときには使えそう
### 参考
https://qiita.com/0905Tom/items/3e305a2bd2bc57c663fa


# 結論
## XLPagerTabStripに決定！
### 理由
1. ライブラリのStar数でも、アプリに使用されている数でも、PageMenuを上回っていたから。
2. CharhageとCocoa Podsの両方でインストール可能だったから。
3. 龍之介さんの記事見つけた（笑）↓
https://qiita.com/Riscait/items/88a5f6c11ce42e6f6624

**Comment by yamatatsu10969** [comment]
@Riscait 
レビュー？　お願いします！

**Comment by riscait** [comment]
比較お疲れ様でした！とても分かりやすいです♪
XLPagerTabStripに決定了解です🙆‍♂️
僕の記事も懐かしいです、よく見つけましたね☺️笑

異論ありません！
