### ISSUE TITLE
[開発者全員] ライブラリ管理のためのCarthageをインストールする

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#35]
### 必要性
ライブラリのインストール・管理に必要です
※このIssueではXcodeは使用しません。Gitも必要ありません

### 期待値

- Homebewについてなんとなく分かる
- Carthageについてどんなものなのか各自調べてみる
- CarthageをMacにインストールし、使える環境にする

### タスク内容
- [x] Mac用パッケージマネージャーHomebrew（便利）をインストールする
https://brew.sh/index_ja
- [x] brewコマンドで、Carthageをインストールする
`$ brew install carthage`

参考URLの②まで終えられることがゴール

### 参考URL・画像など
https://qiita.com/fuwamaki/items/5e6e9c18e5a0b1d7199e

**Comment by riscait** [comment]
龍之介、brew install carthage完了しました！

**Comment by eyener3** [comment]
完了いたしました^-^💡

**Comment by yamatatsu10969** [comment]
やまたつ完了しました！

**Comment by riscait** [comment]
こちらも一旦完了ですので、Closeします！

**Comment by riscait** [comment]
@stmtk1 向けにReoponします

**Comment by naipaka** [comment]
ないぱか完了しました！

**Comment by minmin0530** [comment]
ヨシキ完了しました！
