### ISSUE TITLE
実装前のファイル作成の流れをWikiにまとめる

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#36]
### 必要性

- 初心者にやさしい共同開発として誰もがわかる手順の記載が必要である。

- メンバー（主にPM）の負担を減らす目的もある。

### 期待値

- わからないことはWikiを見れば理解できるようになる。

- メンバー各自の負担の軽減

- はじめて開発に挑戦する人の心的ハードルを下げる

--
画像の反映がうまくされないので一時中断。

**Comment by riscait** [comment]
とても良いですね！☺️
用意できたら、みんなにやさしくなりますね✨

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
ありがとうございます^-^
少しずつ編集・修正していこうと思います💡

**Comment by eyener3** [comment]
画像の貼り付けに一手間かかりそうなので、他のタスクが落ち着いてから続きやります^-^
