### ISSUE TITLE
GitHubの主な機能・用途についてWikiにまとめる

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#40]
### 必要性

- 初心者にやさしい共同開発として誰もがわかる手順の記載が必要である

- メンバー（主にPM）の負担を減らす目的

### 期待値

- GiHubの基本的なことが理解できるになる

- メンバー各自の負担の軽減

- はじめて開発に挑戦する人の心的ハードルを下げる

**Comment by riscait** [comment]
@eyener3 
作成ありがとうございます！
@yasasii-team/ios 
気づいたことあったら編集・追記するようにします！
