### ISSUE TITLE
タスク(挑戦?)のデータ構造を考える

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#42]
### 必要性
ユーザーが選択し、実行する「タスク」
データベースに保存することになるが、どんなプロパティ(値)を持つべきか議論して決めていきたい。

### プロパティ候補

- 一意のID
- 名前
- 進捗状態(ストック・進行中・達成済み)
- 作成した日時
- 開始した日時
- 達成した日時

**Comment by eyener3** [comment]
データベースのプロパティについて調べてみましたが
あまりわからなかったので質問させてください^-^。

データベースのプロパティは
「ユーザーがアクションを起こした時に、
どういった値で、管理者側(？)にデータとして表示させるか」
という認識で相違ないでしょうか..？><

**Comment by riscait** [comment]
@eyener3 たぶんイメージはあってるかと思います！
データを表示させるかというよりも、
なんのデータを保存するか、です👌
データベースに何を記録するかを決めようってことですね😌

言葉にすると難しい…うまく伝わりましたかね？🧐

**Comment by eyener3** [comment]
@Riscait
なんのデータを保存するか、ですね💡
ありがとうございます！
ばっちりイメージできましたっ

保存したデータベースは、
管理者側で見ることができるのですよね^-^
データを基に何か分析もするのでしょうか？
ただ、どのデータを取得するか、
というだけなのでしょうか^-^？

用途や目的によって、
少しわたしの意見が変わりそうだったので
再度、質問させていただきました^-^！

**Comment by riscait** [comment]
@eyener3 
良かった☺️

レルムで保存したデータは、各ユーザーのローカル（iPhone内）に保存されるので開発者が見ることはできません(o^^o)
なので分析はできないですね(＞＜)b

単に、アプリをKILLしてもデータを保持するのに使います👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
@Riscait 
ありがとうございます^-^
視覚的に確認するものではなく、あくまでも保存のお話しなのですね💡

アプリをKILLしたとしてもデータを保持する用途であれば
「進捗状態(ストック・進行中・達成済み)」が保存されるのはいいなと思いました^-^！

**Comment by naipaka** [comment]
プロパティ候補に上がっているプロパティで十分だと思います！
ただ一点、一意のIDの用途がいまいちわからなかったのですが、削除したりする時に使う感じでしょうか？？

**Comment by riscait** [comment]
やばい記憶が…
検索したり、特定したりするのに必要かと思います😊

**Comment by riscait** [comment]
サーバーにあげて共有するものでもないので、連番でいいのかなと思ってます！

進捗状態ですが、進捗画面でチェックつけてある状態と、本当の？達成済み状態は分けた方が良いのかな？次のサイクルに入った時点で達成済みにする感じかなぁ🤔

**Comment by naipaka** [comment]
なるほど、検索っていうのはユーザーが使う検索ですか？？取得するときの検索です？？
やっぱりIDから検索した方がいいんですかね🤔

**Comment by naipaka** [comment]
あー達成の状態分けたほうがいいですかねー、達成日時がチェックしたときの日時で、タスク画面で表示するとき日時も達成日時なら連動しててもいいかなとも思うんですけどどうでしょう？
分けたほうがメリットありそうですかね？🤔
ちなみにデータとは関係ないですが、サイクルの中で終わらなかったときのタスクってどうなるんでしょう…ストックに行く感じかなと勝手に思ってましたが！

**Comment by riscait** [comment]
１つのタスクを特定したい時、タスクの名前や日付って他のタスクと被る可能性がありますよね？
僕も詳しいわけじゃうまく説明できず(>_<)
http://karoten512.hatenablog.com/entry/2017/11/22/232120
https://www.google.co.jp/amp/s/www.graffe.jp/blog/533/amp/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by riscait** [comment]
> 達成日時がチェックしたときの日時で、タスク画面で表示するとき日時も達成日時なら連動しててもいいかなとも思うんですけどどうでしょう？

チェックボタンを押したら、進捗は「達成済み」になって達成済み日時も入れて達成済み一覧に表示？
だと、進捗画面に表示するときの条件がないかな？と思いました🤔
進捗画面に表示するか否かはUserDefaultsを使うとか？

> ちなみにデータとは関係ないですが、サイクルの中で終わらなかったときのタスクってどうなるんでしょう…ストックに行く感じかなと勝手に思ってましたが！

確かに！ストックに行くかそのまま次のサイクルに引き継ぐかの2択ですね！
仕切り直した方が良いと思うので「ストックに行く」に賛成です！

**Comment by naipaka** [comment]
> １つのタスクを特定したい時、タスクの名前や日付って他のタスクと被る可能性がありますよね？

確かに！削除するときとかIDから検索して削除した方がいいですね…！自分のアプリだとtableの列番号から検索して削除してたので考えが及ばなかった…
参考URLまでありがとうございます！

**Comment by naipaka** [comment]
> チェックボタンを押したら、進捗は「達成済み」になって達成済み日時も入れて達成済み一覧に表示？
> だと、進捗画面に表示するときの条件がないかな？と思いました🤔

なるほど。確かに。勝手に「進行中かつ開始した日時が期間内のもの」を表示するものだと思ってましたが、それだと期間を変更したときの事考えたらめんどくさいですね！
進捗状況（進行中、実施済み、ストック）と達成状況（未達成、達成）の２つ項目作りましょう！

**Comment by naipaka** [comment]
一度整理すると、

- 一意のID
- 名前
- 進捗状態（進行中、実施済み、ストック）
- 達成状況（未達成、達成）
- 作成した日時（タスクを追加した日時）
- 実施済みにした日時
- 期間の開始日時
- 期間の終了日時

ですかね

**Comment by naipaka** [comment]
> * 期間の開始日時
> * 期間の終了日時

これいらないですかね？？特に使う用途が思いつきませんでした！

**Comment by naipaka** [comment]
とりあえず一度これでレルムオブジェクトを作成しようと思います！
使っていてここ変えたいなどあればまた話し合いましょう！

- 一意のID
- 名前
- 進捗状態（進行中、実施済み、ストック）
- 達成状況（未達成、達成）
- 作成した日時（タスクを追加した日時）
- 実施済みにした日時

**Comment by riscait** [comment]
ありがとうございます😊
進捗状態と達成状況ってわかる必要ありますかね？
進捗状態（後でやる・挑戦中・達成見込・達成済み）
で良いのかな？と思いました🤔（どうなんだろ？）

**Comment by naipaka** [comment]
あ、確かに分けなくても良いですね！！
達成状況の"未達成"の中に全て進捗状態が含まれてますね:persevere:

以下で作成していきます！
- 一意のID
- 名前
- 進捗状態（進行中、実施済み、ストック）
- 達成状況（未達成、達成）
- 作成した日時（タスクを追加した日時）
- 実施済みにした日時

**Comment by naipaka** [comment]
あ、確かに分けなくても良いですね！！
達成状況の"未達成"の中に全て進捗状態が含まれてますね、
ちゃんと考えられてなかった…スミマセン😣

では以下で作成していきます！
- 一意のID
- 名前
- 進捗状態（後でやる・挑戦中・達成見込・達成済み）
- 挑戦タスクを追加した日時
- 実施済みにした日時（チェックをつけた日時）
