### ISSUE TITLE
達成済みタスク・ストックしたタスク表示画面の構成を考えて必要なファイルを決める

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#44]
### 必要性
実装の事前準備として

### 期待値

- Views
  - .storyboard

- Controller 
  - VC.swift

### 参考URL・画像など

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yamatatsu10969** [comment]
# ファイル用意案
* Views
  * ShowIPPO.storyboard
* VC
  * ShowIPPOVC.swift

## 詳細画面追加時
* Views
  * ShowIPPO.storyboard
* VC
  * ShowIPPOVC.swift
  * ShowIPPODetailVC.swift

Viewsは同じ箇所で編集したいと思います。
@Riscait 
現場ではどのように管理しているんですかね？
１つの画面に、１つのVCがいるイメージですかね？

**Comment by riscait** [comment]
@YamaTatsu10969 
> 現場ではどのように管理しているんですかね？
> １つの画面に、１つのVCがいるイメージですかね？

現場によりますが、個人的にチーム開発では 1VC = 1storyboard が良いかな、と思います👍
今後、もしかしたら一覧画面と詳細画面で別の人が並行して作業したりするかもしれないので👌

`xxxList.storyboard` と `xxxDetail.storyboard`に分ける感じですかね😊

あ、確か使用するライブラリはそれぞれの画面をVCで用意するんでしたよね？
考えてみたんですが、
達成済みは `AchievedIPPO.*`、ストックは`StockedIPPO.*`という名前が良いかも？
と思いました👍

**Comment by yamatatsu10969** [comment]
> あ、確か使用するライブラリはそれぞれの画面をVCで用意するんでしたよね？
考えてみたんですが、達成済みは AchievedIPPO.*、ストックはStockedIPPO.*という名前が良いかも？
と思いました👍

そうなんですね！実装方法は知らなかったです！それぞれの画面をVCで用意するのなら、龍之介さんのアイデアが良さそうです！作成いたします！

> 現場によりますが、個人的にチーム開発では 1VC = 1storyboard が良いかな、と思います👍今後、もしかしたら一覧画面と詳細画面で別の人が並行して作業したりするかもしれないので👌xxxList.storyboard と xxxDetail.storyboardに分ける感じですかね😊

そうなんですね！現場のことも教えていただきありがとうございます！そちらでまずファイル作成を行います！

**Comment by yamatatsu10969** [comment]
## ファイル用意案
* Views
  * IPPOList.storyboard
  * IPPODetail.storyboard
* VC
  * AchievedIPPO.swift
  * StockedIPPO.swift

こちらでファイル作成します！

**Comment by yamatatsu10969** [comment]
> AchievedIPPO.swift
> StockedIPPO.swift

こちらは、VCはつけなくても大丈夫ですかね？

**Comment by riscait** [comment]
View ControllerにはVC付けましょう〜👍

Detail画面って、まだ実装しないですよね？

あと、二つの子VCをまとめる親VCが必要かと思います👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yamatatsu10969** [comment]
> Detail画面って、まだ実装しないですよね？

まだやらないので、後から追加することにします！

> あと、二つの子VCをまとめる親VCが必要かと思います👌

確かにそうですね。
親VCの名前どうしましょう。
現状の案では、ListedIPPOVC.swift にしようと思っています！


ファイル用意案
* Views
  * IPPOList.storyboard
  * (IPPODetail.storyboard)今回は追加しないが、後ほど実装する時に入れる。
* VC
  * ListedIPPOVC.swift (親)
  * AchievedIPPOVC.swift
  * StockedIPPOVC.swift

**Comment by riscait** [comment]
ListedIPPOVC良いと思います👍

1VC=1SBなら、
ListedIPPO.storyboard
AchievedIPPO.storyboard
StockedIPPO.storyboard
が必要ではないでしょうか？🧐

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yamatatsu10969** [comment]
かしこまりました！作成いたします！

**Comment by yamatatsu10969** [comment]
その構成でPR出しますね！

**Comment by yamatatsu10969** [comment]
## ファイル用意案
* Views
  * (IPPODetail.storyboard)
  * ListedIPPO.storyboard
  * AchievedIPPO.storyboard
  * StockedIPPO.storyboard
* VC
  * (IPPODetailVC.swift)
  * ListedIPPOVC.swift (親)
  * AchievedIPPOVC.swift
  * StockedIPPOVC.swift

Detailは後から！！！
