### ISSUE TITLE
進捗画面のライブラリ選定

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#45]
### 必要性
インジーケーターとチェックボタンにライブラリを使うため。

### 期待値
ライブラリを選定することにより、必要な機能を実現する。

### タスク内容
- 参考記事の洗い出し （良さげな記事を載せる）
- インジケーターのライブラリを決める
- チェックボタンのライブラリを決める

### その他の情報
参考記事はインジケーター・チェックボタンに関係ないものも多少含まれる。

**Comment by eyener3** [comment]
【色んなiOSアプリが使っているオープンソースライブラリを調べた】
[https://qiita.com/inoue0426/items/d97a0bca18ec5f91d839](url)

【調べたiOSのオープンソースライブラリをリスト化してみました】
[http://smsurf.app-rox.com/iosl/](url)

【iOSとSwift用のリソースとライブラリのリスト。】
[https://github.com/Ramshandilya/iOSRepo](url)

【iOSライブラリをまとめてるサイトのまとめ】
[https://qiita.com/homyu/items/e36faf42e64577f76692](url)

インジケーターと検索すると、ローディングや円グラフのようなものしか出てこないので、
設計書のようなインジケーターのライブラリを、もう少し探す必要がある。

**Comment by eyener3** [comment]
インジケーターについて。
進捗の可視化のバーのことを
ProgressBar（プログレスバー）と呼ぶらしい。
![スクリーンショット 2019-04-12 04 19 16](https://user-images.githubusercontent.com/45029154/55985157-2e3ebc00-5cda-11e9-902f-924d92afcf8c.png)

ProgressBarが円形のものばかり。。
しかし、まっすぐの横棒をコーディングで円にしているとも書いてあった。
つまりは、円にしている部分のコードなしで考えたら、横棒になるのでは..？
（コーディングしながら変化を確かめてみる。）
[https://github.com/kentya6/KYCircularProgress](url)

※横棒の少しだけありました^-^
[https://www.cocoacontrols.com/search?q=ProgressBar](url)

**Comment by eyener3** [comment]
ライブラリ、だいたい決まりました。

1.ProgressBar
[https://github.com/kentya6/KYCircularProgress](url)
[https://pippi-pro.com/swift-how-to-use-mbcircularprogressbar](url)

2.チェックボタン
[https://github.com/rizumita/CTCheckbox#license](url) 
[https://github.com/rakaramos/OnOffButton](url)

3.ボタン（アニメーション付き）
[https://github.com/zoonooz/ZFRippleButton](url) 

※ライセンスの条件付きのものもあるようです。
あまりわからないので、ライセンスについて調べてみる。

### **参考記事**
- iOSの開発でお気に入りのライブラリN選
[https://qiita.com/u651601f/items/08500df9246a6c208241](url)

- iOSで気になるライブラリ Swift編
[https://qiita.com/PGMY/items/cf2d34e335f03f821f72#%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3](url)

**Comment by riscait** [comment]
お疲れ様です！
とても詳しく、ありがとうこざいます！
円形のものばかりなんですね〜🧐
後ほど僕も勉強のため詳しく見させてもらいます♪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
