### ISSUE TITLE
SwiftLintを導入する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#46]
**※要詳細**

### タスク内容
- [ ] 
- [ ] 
- [ ] 

### 参考URL・画像など
https://qiita.com/uhooi/items/bf888b53b4b8210108aa

**Comment by eyener3** [comment]
![スクリーンショット 2019-04-12 03 31 59](https://user-images.githubusercontent.com/45029154/55982793-a0ac9d80-5cd4-11e9-8a75-9140a8b866d2.png)
↑ここまで上手くいきました^-^

以下を、これから行ないます。
![スクリーンショット 2019-04-12 03 39 27](https://user-images.githubusercontent.com/45029154/55982795-a30ef780-5cd4-11e9-81cd-3402d3ce7dc3.png)

"プロジェクトのルートディレクトリに .swiftlint.yml を作成"
ルートディレクトリ = 最初・最上位のディレクトリということは把握しました。

..となると、以下がルートディレクトリになるのでしょうか？
![スクリーンショット 2019-04-12 03 48 14](https://user-images.githubusercontent.com/45029154/55983351-e5850400-5cd5-11e9-9a92-d82a6d949e2f.png)

![スクリーンショット 2019-04-12 03 51 16](https://user-images.githubusercontent.com/45029154/55983502-3eed3300-5cd6-11e9-9a65-e20c5a06a571.png)

よろしくお願いします^-^

**Comment by riscait** [comment]
@eyener3 
さっそくの実行ありがとうございます！

①これって #41 と同じブランチを使っていませんか？
基本別のIssueであれば別のブランチを最近のmasterから切って取りかからなくてはいけません。

②ymlファイルの作成、設定はおそらく好みによって変わってきますので、議論して詰めていきたいですね！各プロパティ（デフォルト設定）の意味など調べていただけると嬉しいですが、別Issue作りますね👌
追記: SwiftLintのルール選定(ymlファイルの中身）Issueはすでに作っていました
#47 
こちらで行なっていきましょう！

③通常Xcodeプロジェクトのルートディレクトは `Xxx.xcodeproj` ど同じ階層となります🙆‍♂️
<img width="929" alt="スクリーンショット 2019-04-12 10 54 36" src="https://user-images.githubusercontent.com/8737743/56006899-af657580-5d11-11e9-99c7-8322bf0de0e0.png">

僕の場合こういうローカルディレクトリ構成になっていますが、
riscait/XcodeProjects/Stepippo-iOS/Stepippo/Classes...

あいなーさんの場合は
katouayamna/Steppipo/Classes...
となっている？🤔
Userディレクトリの下にいきなりStepippoルートディレクトリがある？？

**Comment by eyener3** [comment]
見落としていました
ありがとうございます^-^💡
