### ISSUE TITLE
SwiftLintのルールを選定する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#47]
### タスク内容
- [ ] 
- [ ] 
- [ ]

**Comment by eyener3** [comment]
公式
https://github.com/realm/SwiftLint/blob/master/Rules.md

SwiftLintの全ルール一覧(Swift 4.2版)
https://qiita.com/uhooi/items/7f5d6cf2b240f60ba1ed

既存PJにSwiftLintを導入したら大変だった話
https://speakerdeck.com/uhooi/setup-swiftlint
