### ISSUE TITLE
Carthageを使い、XLPagerTabStripを導入する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#48]
### 必要性
画面内ページ切り替えにXLPagerTabStripを使用する

### 期待値
XLPagerTabStripをCarthageを使ってStepippoプロジェクトに組み込む。
エラーなくビルドすることができる

### タスク内容
- [x] Carthageをインストールして使えるようにする(#35)
- [x] Carthageを使い、ライブラリをプロジェクトにインストールする
- [ ] プロジェクトをビルドしてエラーがないことを確認する

### その他の情報
Carthage、ライブラリは最新版(Latest)を使う。

### 参考URL・画像など

**Comment by yamatatsu10969** [comment]
@Riscait 
ビルドは通るようになりましたが、立ち上げた瞬間にimage not found というエラーが出ます。。。
画面は立ち上がっているんですが。
なぜかがわからないです。。。

```
dyld: Library not loaded: @rpath/XLPagerTabStrip.framework/XLPagerTabStrip
  Referenced from: /Users/yamamototatsuya/Library/Developer/CoreSimulator/Devices/BCE52C0C-B47E-411F-87AD-BFEE640DE816/data/Containers/Bundle/Application/183B6395-F016-4220-AAD1-BC8254E05931/Stepippo.app/Stepippo
  Reason: image not found
```

<img width="721" alt="スクリーンショット 2019-04-14 10 38 02" src="https://user-images.githubusercontent.com/43805056/56087216-66dcc200-5ea1-11e9-8f99-9a767ca6a81a.png">

**Comment by riscait** [comment]
@YamaTatsu10969 
> プロジェクトファイルのGeneralタブから、「Linked Frameworks and Library」にある➕ボタンを押す
> 対象のファイルを選択(なお今回作成したライブラリは下記のディレクトリに保存される⇨Carthage/Build/iOS)
> Build Phasesタブに移動し、➕ボタンから、「New Run Script Phase」を選択
> 「Shell」の下にある黒部分に以下のコマンドを記述します。
> 　/usr/local/bin/carthage copy-frameworks
> 
> 「input Files」にて＋ボタンを押し、以下のようにframeworkの情報を記述　します。
> $(SRCROOT)//Carthage/Build/iOS/xxx.framework


ここらへんてもう完了済みですよね？
https://hirochan-blog5.com/2018/08/25/relam/
http://mtimsno.hatenablog.jp/entry/2017/04/23/150223

**Comment by yamatatsu10969** [comment]
> プロジェクトファイルのGeneralタブから、「Linked Frameworks and Library」にある➕ボタンを押す
対象のファイルを選択(なお今回作成したライブラリは下記のディレクトリに保存される⇨Carthage/Build/iOS)


ここまでしかやっていませんでした！トライします！
