### ISSUE TITLE
[Github] URLとTopicsを設定する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#6]
1. EditからこのリポジトリのURLを追加
2. Manege topicsでこのリポジトリのTopics（タグのようなもの）を追加する
例: ios, swift

<img width="1015" alt="スクリーンショット 2019-03-23 16 29 08" src="https://user-images.githubusercontent.com/8737743/54863188-e981ce00-4d88-11e9-92e6-9fc4d1a02db7.png">

**Comment by eyener3** [comment]
こちら設定いたしましたのでCloseいたします^-^💡
Topicsは自由に追加してくださいねっ♪

**Comment by riscait** [comment]
ありがとうございます！
