### ISSUE TITLE
[XLPagerTabStrip]Carthageのライブラリ状況を全員合わせる[bootstrap]

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#62]
### 必要性
新しくcarthageにてライブラリがインストールされ、masterにマージされた場合、
ライブラリ依存に対応するために、全員ライブラリを手元でビルドする必要がある

(carthageでインストールしたビルド成果物そのものはリポジトリにpushしていないため)

### 期待値
エラーなくライブラリ使うことができる

### タスク内容
- [ ] 最新のmasterブランチで、「ライブラリがないよエラー」が出ることを確認する
- [ ] carthage bootstrap —platform iOS コマンドを実行
- [ ] エラーが消えてビルドできることを確認

**Comment by eyener3** [comment]
🙆‍♀️完了しました。

**Comment by riscait** [comment]
現開発メンバー全員が完了できましたのでCloseします！
また必要になったらReoponするかもしれません。
