### ISSUE TITLE
達成済みIPPO表示画面を実装する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#70]
### 機能の必要性
XLPagerTabStriperを使う前に、おそらく2VCそれぞれの画面を実装することになると思います。
（2つ作り終わったっらXLPagerTabStriperでまとめる）

### 実装の期待値
画面定義書を参考に、UITableViewで達成済みIPPOの画面を実装できる

### 検討した実装案
Realmが必要

**Comment by Sab-swiftlin** [comment]
@Riscait 
画面定義書というのはどこかに用意されているのもでしょうか？
それとも、Sketchのプロトタイプを指しているのでしょうか？

**Comment by riscait** [comment]
各々の担当が作ろうということになってはいたんですが…Sketchのものしかありませんッ🙋‍♂️

**Comment by eyener3** [comment]
わたしもなんだかんだ出来ていませんでした＞＜
開発する上で、大事なことですものね..💡
わたしも、自分なりに考えて、
別の方法で画面定義書、挑戦してみようと思います(＞人＜;)

**Comment by Sab-swiftlin** [comment]
@Riscait 
@eyener3 

ありがとうございます！
現状が知りたかっただけなのでそういうことであれば問題ないです！
ドキュメント作るより実装してた方が楽しいと思いますので、追い追いで良いんじゃないでしょうか。笑
