### ISSUE TITLE
[開発者全員]Carthageのbootstrapコマンドでライブラリ環境を揃える

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#76]
Carthageの導入については #35 を参照

**完了したら、コメントでその旨を書き、アサインを外してください👌**

### 必要性
Carthageで導入したライブラリのビルド成果物はリポジトリに含めていないため、各員手元での
ビルドが必要

### 期待値
以下のライブラリをビルドし、エラーなくライブラリ使うことができる

- [x] XLPagerTabStrip
- [x] Realm

### タスク内容
- [x] `$ carthage bootstrap` コマンドを実行してライブラリをビルドする
- [x] 最新のmasterブランチで、エラーなくビルドできることを確認

**Comment by Koki-Nakamura** [comment]
@Riscait 
対応完了しました！

**Comment by eyener3** [comment]
完了しました^-^💡

**Comment by eyener3** [comment]
シュミレーターでエラー出てしまっているので
ちょっと修正してみます。。

**Comment by naipaka** [comment]
スミマセン…
` Cartfile.resolved `があるディレクトリで` $ carthage bootstrap —platform iOS `を打つと

「 No entry found for dependencies ios, —platform in Cartfile.resolved – please run `carthage update` if the dependency is contained in the project's Cartfile. 」

と出てきます。
文に従って` carthage update `しちゃったんですが、あってますか…？
一応最新のmasterブランチで、エラーなくビルドできることは確認できました！

**Comment by riscait** [comment]
あいなーさんの時と同じエラー文ですね！
@eyener3 の時は確か　`—platform iOS`抜きの `carthage bootstrap `のみでやったような覚えがあります🤔
同じバージョンのフレームワークが導入できていて、エラーが出ていなければ問題ないかと思います！

**Comment by naipaka** [comment]
そうだったのですね！ありがとうございます！

バージョン違ったので、もう一度 `carthage bootstrap` で再度導入しました！
完了したのでアサイン外します！

**Comment by riscait** [comment]
おぉ、成功して良かったです…！
情報共有ありがとうございます😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sab-swiftlin** [comment]
対応しました。

**Comment by minmin0530** [comment]
対応しました！

**Comment by riscait** [comment]
ヨシキさん、アサインしておきましたー！
