### ISSUE TITLE
git ignore を追加する

### ISSUE THREAD

**Issue by yamatatsu10969** [yasasii-team/Stepippo-iOS#8]
git ignoreを入れる練習を誰かができれば良いなと思い作成しました！

**Comment by yamatatsu10969** [comment]
もうあったーwww
どうやって消すんだ？😶

**Comment by yamatatsu10969** [comment]
見つけた。
Close and comment　だ。
Closeします〜

**Comment by riscait** [comment]
起票ありがとうございます！
深く考えずにコピペで追加してしまっていましたー＞＜
これもIssue化すべきでしたね＞＜

**Comment by yamatatsu10969** [comment]
これ絵文字も追加できるんですね！よいですね〜。
一人でgit ignoreはなかなか難しい印象だったんで、練習できたらよかったですね笑
全然OKです！作成ありがとうございます。
projectないと始まりませんからね〜！
