### ISSUE TITLE
各画面にTab Bar Item を追加してアイコンとTitleを設定する

### ISSUE THREAD

**Issue by riscait** [yasasii-team/Stepippo-iOS#88]
### 機能の必要性

**1.  Prog画面 → @eyener3 
2. ListedIPPO画面 -> @YamaTatsu10969 
3. Misc画面 -> @Riscait** 

の3画面はTabBarControllerで管理する画面になるが、アイコンを設定しておかないとTabBarが空白になり各画面の選択がしづらいため必要

### 実装の期待値
TabBarに設定したアイコンとタイトルが表示されること
詳しくは下記の画像を参照

### 検討した実装案
Prog画面
→進捗を表すようなアイコンで、タイトルは「進捗」？
ListedIPPO画面
→リストだと分かるようなアイコンで、タイトルは「IPPO」？
Misc画面
→その他だと分かるようなアイコンで、タイトルは「その他」か「設定」

### 参考URL・画像・スクリーンショット
<img width="1106" alt="スクリーンショット 2019-05-02 20 44 07" src="https://user-images.githubusercontent.com/8737743/57073337-c2210800-6d1b-11e9-942d-e7b4779b9d58.png">

**Comment by eyener3** [comment]
この作業も自分のブランチに切り替えて作業して
commitまでを行なうと良いのでしょうか^-^？
見当違いな質問でしたら申し訳ないです..(⌒-⌒; )

**Comment by riscait** [comment]
> この作業も自分のブランチに切り替えて作業して
> commitまでを行なうと良いのでしょうか^-^？

そうですね！他に作業中でなければ、最新のmasterから新しくブランチを切って作業し、コミット〜プルリクまで行なってください👌

**Comment by riscait** [comment]
3画面（3プルリク）完了したらこのIssueをCloseしましょう〜！

**Comment by riscait** [comment]
あ、設定するのは自分の担当画面だけでOKです！
（追記しました）

**Comment by eyener3** [comment]
承知しました💡
ありがとうございます！

**Comment by riscait** [comment]
アイコンなんですが、「icon8」もオススメです！
（Misc画面の各セルアイコンで使いました）
Macアプリが特に使いやすい…💡

**Comment by eyener3** [comment]
ありがとうございます！
龍之介さんのアイコンいいなぁと思っていました^0^！
icon8 使ってみたいと思います♪

**Comment by riscait** [comment]
いつも、その他(設定)画面は、設定を表す歯車のアイコンか「…(3 dots)」にするか迷う🤔

**Comment by eyener3** [comment]
迷いますね..🤔
タイトルが"設定"だったら歯車、"その他"だったら「…(3 dots)」
というのもありな気がしました💡

**Comment by riscait** [comment]
その他画面、完了しました👌

**Comment by eyener3** [comment]
進捗画面、完了しました^-^💡

**Comment by Sab-swiftlin** [comment]
タスク一覧画面完了しました！
本Issueは閉じますか？

**Comment by riscait** [comment]
あ、そうですね✨
閉じます👌
