### ISSUE TITLE
【進捗画面】Tab Bar Item を追加してアイコンとTitleを設定する

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#92]
関連するIssue #88 

### 機能の必要性
アイコンを設定しておかないとTabBarが空白になり各画面の選択がしづらいため必要

### 実装の期待値
TabBarに設定したアイコンとタイトルが表示されること

### その他の情報
進捗画面が確かホーム画面になるので
家のアイコンでもいいかなぁと検討中。

### 参考URL・画像・スクリーンショット
参考サイト：http://icooon-mono.com/category/sign/
![スクリーンショット 2019-05-02 22 20 16](https://user-images.githubusercontent.com/45029154/57078073-7de83480-6d28-11e9-8ce7-ccc89b6087a3.png)

**Comment by riscait** [comment]
確かに進捗だけでなくタスク設定画面に行ったり、色々しますもんね💡
ホームアイコンも良いと思います♪

**Comment by eyener3** [comment]
ありがとうございます^0^！
またより良い案がでたら検討することにして、
いまのところホームアイコンにしてみます💡

**Comment by eyener3** [comment]
タスクアイコン、かわいいなぁ。。
こっちにしてみよう。
![スクリーンショット 2019-05-03 00 11 18](https://user-images.githubusercontent.com/45029154/57085862-07533300-6d38-11e9-8e37-982fed60f770.png)

**Comment by eyener3** [comment]
シュミレーターでテストしたところ、
ビルドエラーが出てしまいました。＞＜
![スクリーンショット 2019-05-03 02 48 22](https://user-images.githubusercontent.com/45029154/57095556-2eb4fa80-6d4e-11e9-8c81-be31310ce966.png)

エラー文を検索したところ、
[開発者全員]Carthageのbootstrapコマンドでライブラリ環境を揃える #76 
こちらを行なっていないためにエラーになっているようでした。

こういった場合は、
上記の #76 を優先的に行なうのがいいのですよね..><💡

masterについて理解がもう一歩及ばないのですが
**#76 のようなタスクでは、ブランチを切らずに下記のように
masterにチェックアウトしてGitを実行するので合っていますでしょうか^-^**
#76 の場合も、新たにブランチを切る必要があるのでしょうか？
![スクリーンショット 2019-05-03 02 55 02](https://user-images.githubusercontent.com/45029154/57095877-dc280e00-6d4e-11e9-9524-b607a346838e.png)

ブランチをmasterからチェックアウトしたらエラーは消えてくれましたが..
![スクリーンショット 2019-05-03 03 20 42](https://user-images.githubusercontent.com/45029154/57097376-8f463680-6d52-11e9-82e3-f0c36bfebe7e.png)


（どちらのIssueで質問させていただくか悩みましたが、こちらにまとめてさせいていただきました。）
すみませんが、よろしくお願いします🙇‍♀️

**Comment by riscait** [comment]
@eyener3 
#76 のタスクについては、あくまで各員のローカルの環境を合わせるのが目的なので、ブランチ作成したりコミットする必要はありません👌
なので、どのブランチで行なっても良い作業となります（ブランチは関係ない）
bootstrapコマンド実行後にエラーが出なければOK！

念の為、以下のディレクトリを確認してみてRealm.frameworkがあると思うので確認してみてください💡
Stepippo-iOS/Carthage/Build/iOS/Realm.framework
Stepippo-iOS/Carthage/Build/iOS/RealmSwift.framework

**Comment by eyener3** [comment]
ありがとうございます^-^！
#76 上手くいきました🙇‍♀️
ディレクトリの確認も行ない、該当する2つがありました。
ありがとうございました💡
