### ISSUE TITLE
【進捗画面】配置したパーツをStackViewでまとめる

### ISSUE THREAD

**Issue by eyener3** [yasasii-team/Stepippo-iOS#98]
### 機能の必要性
AutoLayoutを設定するViewをグルーピングして、まとめて制約を設定する

### 実装の期待値

- 各パーツがStackViewに内包されている

- 縦向き・横向きに対して、文字切れや変な余白がうまれない

- iPhone SE ~ iPhone XS Max でレイアウトが崩れず表示されること

### 参考URL・画像・スクリーンショット
StackViewの進め方
https://qiita.com/merrill/items/04be7d2222cd70dd6408

龍之介さんが作成してくださったSketch
https://sketch.cloud/s/rlRVq/l1g7Dvz/play

![Stepippo進捗画面参考-3](https://user-images.githubusercontent.com/45029154/57152935-f4ac2d00-6e0f-11e9-99f1-b3ca2ca2341b.jpg)

**Comment by riscait** [comment]
期待値に、
iPhone SE ~ iPhone XS Max でレイアウトが崩れず表示されること
を追加しました！

**Comment by eyener3** [comment]
> 期待値に、
> iPhone SE ~ iPhone XS Max でレイアウトが崩れず表示されること
> を追加しました！

追加ありがとうございます＾ー＾！

**Comment by riscait** [comment]
StackViewに入れるところまで完了
残タスク: StackViewの属性に適切なものを設定して配置を整える
StackViewにAuto Layoutの制約をつけてSE〜XS Maxで表示を崩れないようにする

以上は新しくissueを作る予定です

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eyener3** [comment]
> StackViewに入れるところまで完了
> 残タスク: StackViewの属性に適切なものを設定して配置を整える
> StackViewにAuto Layoutの制約をつけてSE〜XS Maxで表示を崩れないようにする
> 
> 以上は新しくissueを作る予定です

ありがとうございますm(._.)m！！
